if(NOT DEFINED OUTPUT OR "${OUTPUT}" STREQUAL "")
  message(FATAL_ERROR "GenerateDarwinBlasAliasList.cmake requires OUTPUT.")
endif()

if(NOT DEFINED INPUTS OR "${INPUTS}" STREQUAL "")
  message(FATAL_ERROR "GenerateDarwinBlasAliasList.cmake requires INPUTS.")
endif()

if(DEFINED NM AND NOT "${NM}" STREQUAL "")
  set(_scalapack_nm "${NM}")
else()
  set(_scalapack_nm "nm")
endif()

# Scan BLAS/LAPACK libraries for exported symbols.
set(_scalapack_nm_output "")
foreach(_scalapack_lib IN LISTS INPUTS)
  if(IS_ABSOLUTE "${_scalapack_lib}" AND EXISTS "${_scalapack_lib}")
    execute_process(
      COMMAND "${_scalapack_nm}" -gU "${_scalapack_lib}"
      RESULT_VARIABLE _scalapack_nm_result
      OUTPUT_VARIABLE _scalapack_lib_nm_output
      ERROR_VARIABLE _scalapack_nm_error
    )
    if(NOT _scalapack_nm_result EQUAL 0)
      message(FATAL_ERROR
        "Failed to inspect ${_scalapack_lib} with ${_scalapack_nm}: ${_scalapack_nm_error}")
    endif()
    string(APPEND _scalapack_nm_output "${_scalapack_lib_nm_output}\n")
  endif()
endforeach()

if("${_scalapack_nm_output}" STREQUAL "")
  message(FATAL_ERROR "No BLAS/LAPACK libraries were available to generate a Darwin alias list.")
endif()

# Collect all exported plain symbols and _64_-suffixed symbols.
string(REPLACE "\n" ";" _scalapack_nm_lines "${_scalapack_nm_output}")
set(_scalapack_exported_symbols "")
set(_scalapack_suffix64_symbols "")

foreach(_scalapack_line IN LISTS _scalapack_nm_lines)
  string(STRIP "${_scalapack_line}" _scalapack_line)
  if(_scalapack_line STREQUAL "")
    continue()
  endif()

  string(REGEX MATCH "(_[a-z0-9_]+_)$" _scalapack_plain_symbol_match "${_scalapack_line}")
  if(_scalapack_plain_symbol_match)
    list(APPEND _scalapack_exported_symbols "${CMAKE_MATCH_1}")
  endif()

  string(REGEX MATCH "(_[a-z0-9_]+_64_)$" _scalapack_suffix64_symbol_match "${_scalapack_line}")
  if(_scalapack_suffix64_symbol_match)
    list(APPEND _scalapack_suffix64_symbols "${CMAKE_MATCH_1}")
  endif()
endforeach()

list(REMOVE_DUPLICATES _scalapack_exported_symbols)
list(REMOVE_DUPLICATES _scalapack_suffix64_symbols)

# For every _64_-suffixed symbol, emit an alias from the plain name to the
# suffixed name — unless the BLAS library already exports the plain name.
# This covers all consumers (libscalapack and test executables) without
# needing to know which symbols each target references.
set(_scalapack_alias_lines "")
foreach(_scalapack_suffix64_symbol IN LISTS _scalapack_suffix64_symbols)
  string(REGEX REPLACE "_64_$" "_" _scalapack_plain_symbol "${_scalapack_suffix64_symbol}")
  list(FIND _scalapack_exported_symbols "${_scalapack_plain_symbol}" _scalapack_plain_index)
  if(_scalapack_plain_index EQUAL -1)
    string(APPEND _scalapack_alias_lines
           "${_scalapack_suffix64_symbol} ${_scalapack_plain_symbol}\n")
  endif()
endforeach()

if("${_scalapack_alias_lines}" STREQUAL "")
  message(FATAL_ERROR
    "No suffixed BLAS/LAPACK symbols requiring Darwin aliases were found in ${INPUTS}.")
endif()

file(WRITE "${OUTPUT}"
     "# Generated by GenerateDarwinBlasAliasList.cmake\n${_scalapack_alias_lines}")
